const AUTH_KEY='nyroxhub_users_v1',SESSION_KEY='nyroxhub_session_v1';
const getUsers=()=>JSON.parse(localStorage.getItem(AUTH_KEY)||'[]');
const saveUsers=u=>localStorage.setItem(AUTH_KEY,JSON.stringify(u));
function userId(){let n;do{n=Math.floor(100000+Math.random()*900000)}while(getUsers().some(u=>u.id===n));return n}
function currentUser(){const id=localStorage.getItem(SESSION_KEY);return getUsers().find(u=>String(u.id)===id)||null}
function authPanel(mode='login'){const r=mode==='register';openModal(`<div class="auth-panel"><div class="auth-icon">${r?'✦':'◈'}</div><span class="eyebrow">NYROX ACCOUNT</span><h3>${r?'Ստեղծիր հաշիվ':'Բարի վերադարձ'}</h3><p class="muted">${r?'Գրանցվիր և ստացիր քո եզակի 6-նիշանոց ID-ն։':'Մուտք գործիր քո NyroxHub պրոֆիլ։'}</p>${r?'<label>Անուն<input id="authName" autocomplete="name" placeholder="Քո անունը"></label>':''}<label>Էլ․ փոստ<input id="authEmail" type="email" autocomplete="email" placeholder="you@example.com"></label><label>Գաղտնաբառ<input id="authPass" type="password" autocomplete="current-password" placeholder="••••••••"></label><button class="btn primary full" id="authSubmit">${r?'Գրանցվել':'Մուտք գործել'}</button><button class="auth-switch" id="authSwitch">${r?'Արդեն ունե՞ս հաշիվ։ Մուտք գործիր':'Նոր ե՞ս։ Ստեղծիր հաշիվ'}</button><small class="security-note">Frontend demo․ իրական authentication-ի համար պետք է backend/database։</small></div>`);document.querySelector('#authSubmit').onclick=()=>submitAuth(r);document.querySelector('#authSwitch').onclick=()=>authPanel(r?'login':'register')}
function submitAuth(r){const email=document.querySelector('#authEmail').value.trim().toLowerCase(),pass=document.querySelector('#authPass').value;const name=r?document.querySelector('#authName').value.trim():'';if(!email||!pass||(r&&!name))return toast('Լրացրու բոլոր դաշտերը');let users=getUsers();if(r){if(users.some(u=>u.email===email))return toast('Այս email-ը արդեն գրանցված է');const u={id:userId(),name,email,password:pass,createdAt:new Date().toISOString()};users.push(u);saveUsers(users);localStorage.setItem(SESSION_KEY,String(u.id));closeModal();toast(`Բարի գալուստ, ${name} ✓`)}else{const u=users.find(x=>x.email===email&&x.password===pass);if(!u)return toast('Email-ը կամ գաղտնաբառը սխալ է');localStorage.setItem(SESSION_KEY,String(u.id));closeModal();toast('Մուտքը հաջողվեց ✓')}refreshProfileUI()}
function profilePanel(){const u=currentUser();if(!u)return authPanel();openModal(`<div class="profile"><div class="profile-cover"><div class="avatar">${u.name.charAt(0).toUpperCase()}</div></div><span class="eyebrow">NYROX PROFILE</span><h3>${escapeHtml(u.name)}</h3><div class="profile-id">ID <strong>${u.id}</strong></div><p class="muted">${escapeHtml(u.email)}</p><div class="profile-menu"><button>🛒 Գնումներ</button><button>⚙ Կարգավորումներ</button><button id="logout">↪ Դուրս գալ</button></div></div>`);document.querySelector('#logout').onclick=()=>{localStorage.removeItem(SESSION_KEY);closeModal();refreshProfileUI();toast('Դուրս եկար հաշվից')}}
function escapeHtml(s){return s.replace(/[&<>\'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function refreshProfileUI(){const u=currentUser(),b=document.querySelector('#profileLabel');if(b)b.textContent=u?u.name:'Մուտք'}
document.addEventListener('DOMContentLoaded',()=>{refreshProfileUI();document.querySelector('#profileBtn').onclick=()=>currentUser()?profilePanel():authPanel()});
