const AUTH_KEY='nyroxhub_users_v1',SESSION_KEY='nyroxhub_session_v1',SETTINGS_KEY='nyroxhub_settings_v1';
const getUsers=()=>JSON.parse(localStorage.getItem(AUTH_KEY)||'[]');
const saveUsers=u=>localStorage.setItem(AUTH_KEY,JSON.stringify(u));
const getSettings=()=>Object.assign({dark:true,sound:true},JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}'));
const saveSettings=s=>localStorage.setItem(SETTINGS_KEY,JSON.stringify(s));
function userId(){let n;do{n=Math.floor(100000+Math.random()*900000)}while(getUsers().some(u=>u.id===n));return n}
function currentUser(){const id=localStorage.getItem(SESSION_KEY);return getUsers().find(u=>String(u.id)===id)||null}
function authPanel(mode='register'){const r=mode==='register';openModal(`<div class="auth-panel auth-page"><div class="auth-brand"><div class="auth-logo">N</div><strong>Nyrox<span>Hub</span></strong></div><span class="eyebrow">NYROX ACCOUNT</span><h3>${r?'Ստեղծիր հաշիվ':'Բարի վերադարձ'}</h3><p class="muted">${r?'Գրանցվիր և ստացիր քո եզակի 6-նիշանոց ID-ն։':'Մուտք գործիր քո NyroxHub պրոֆիլ։'}</p>${r?'<label>Անուն<input id="authName" autocomplete="name" placeholder="Քո անունը"></label>':''}<label>Էլ․ փոստ<input id="authEmail" type="email" autocomplete="email" placeholder="you@example.com"></label><label>Գաղտնաբառ<input id="authPass" type="password" autocomplete="current-password" placeholder="••••••••"></label>${!r?'<button class="forgot" id="forgotBtn">Մոռացե՞լ ես գաղտնաբառը</button>':''}<button class="btn primary full" id="authSubmit">${r?'Գրանցվել':'Մուտք գործել'}</button><button class="auth-switch" id="authSwitch">${r?'Արդեն գրանցվա՞ծ ես։ Մուտք գործիր':'Նոր ե՞ս։ Ստեղծիր հաշիվ'}</button><small class="security-note">Իրական password recovery-ի համար backend/email service է անհրաժեշտ։</small></div>`);document.querySelector('#authSubmit').onclick=()=>submitAuth(r);document.querySelector('#authSwitch').onclick=()=>authPanel(r?'login':'register');if(!r)document.querySelector('#forgotBtn').onclick=passwordRecovery}
function submitAuth(r){const email=document.querySelector('#authEmail').value.trim().toLowerCase(),pass=document.querySelector('#authPass').value,name=r?document.querySelector('#authName').value.trim():'';if(!email||!pass||(r&&!name))return toast('Լրացրու բոլոր դաշտերը');let users=getUsers();if(r){if(users.some(u=>u.email===email))return toast('Այս email-ը արդեն գրանցված է');const u={id:userId(),name,email,password:pass,logo:'',createdAt:new Date().toISOString()};users.push(u);saveUsers(users);localStorage.setItem(SESSION_KEY,String(u.id));closeModal();toast(`Բարի գալուստ, ${name} ✓`)}else{const u=users.find(x=>x.email===email&&x.password===pass);if(!u)return toast('Email-ը կամ գաղտնաբառը սխալ է');localStorage.setItem(SESSION_KEY,String(u.id));closeModal();toast('Մուտքը հաջողվեց ✓')}refreshProfileUI()}
function passwordRecovery(){const email=(document.querySelector('#authEmail')?.value||'').trim().toLowerCase();openModal(`<div class="auth-panel auth-page"><div class="auth-brand"><div class="auth-logo">N</div><strong>Nyrox<span>Hub</span></strong></div><span class="eyebrow">PASSWORD RECOVERY</span><h3>Վերականգնել գաղտնաբառը</h3><p class="muted">Մուտքագրիր գրանցված email-ը։</p><label>Էլ․ փոստ<input id="recoveryEmail" type="email" value="${escapeAttr(email)}" placeholder="you@example.com"></label><button class="btn primary full" id="sendRecovery">Ուղարկել email</button><small class="security-note">Frontend-ում email իրական ուղարկել հնարավոր չէ առանց backend/email service-ի։ Այս կոճակը պատրաստ է այդ API-ին միանալու համար և հաջող վճարում/վերականգնում չի կեղծում։</small></div>`);document.querySelector('#sendRecovery').onclick=()=>{const e=document.querySelector('#recoveryEmail').value.trim().toLowerCase();if(!e)return toast('Մուտքագրիր email-ը');if(!getUsers().some(u=>u.email===e))return toast('Այս email-ով հաշիվ չի գտնվել');toast('Վերականգնման հարցումը պատրաստ է ✓')}}
function profilePanel(){const u=currentUser();if(!u)return authPanel('register');openModal(`<div class="profile"><div class="profile-cover"><button class="profile-logo" id="profileLogoBtn">${u.logo?`<img src="${escapeAttr(u.logo)}" alt="Profile logo">`:`<span>${escapeHtml(u.name.charAt(0).toUpperCase())}</span>`}<small>＋</small></button><input id="logoInput" type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" hidden></div><span class="eyebrow">NYROX PROFILE</span><h3>${escapeHtml(u.name)}</h3><div class="profile-id">ID <strong>${u.id}</strong></div><p class="muted">${escapeHtml(u.email)}</p><div class="profile-menu"><button id="settingsBtn">⚙ Կարգավորումներ</button><button id="logout" class="logout">↪ Դուրս գալ</button></div></div>`);document.querySelector('#settingsBtn').onclick=settingsPanel;document.querySelector('#logout').onclick=logout;document.querySelector('#profileLogoBtn').onclick=()=>document.querySelector('#logoInput').click();document.querySelector('#logoInput').onchange=uploadLogo}
function uploadLogo(e){const file=e.target.files[0];if(!file)return;if(file.size>1024*1024)return toast('Լոգոն պետք է լինի մինչև 1MB');const reader=new FileReader();reader.onload=()=>{const users=getUsers(),u=currentUser(),i=users.findIndex(x=>x.id===u.id);users[i].logo=reader.result;saveUsers(users);toast('Profile logo-ն թարմացվեց ✓');profilePanel()};reader.readAsDataURL(file)}
function settingsPanel(){const s=getSettings();openModal(`<div class="settings-panel"><span class="eyebrow">ACCOUNT SETTINGS</span><h3>Կարգավորումներ</h3><div class="setting-row"><div><strong>Մութ էկրան</strong><small>Անջատելու դեպքում կդառնա սպիտակ/բաց</small></div><button class="toggle ${s.dark?'on':''}" id="darkToggle"><i></i></button></div><div class="setting-row"><div><strong>Միացնել հաղորդագրության ձայնը</strong><small>Toast հաղորդագրությունների ձայնային ազդանշան</small></div><button class="toggle ${s.sound?'on':''}" id="soundToggle"><i></i></button></div><button class="setting-link" id="forgotSettings">🔐 Մոռացե՞լ ես գաղտնաբառը</button><button class="setting-link" id="backProfile">← Պրոֆիլ</button><button class="logout setting-logout" id="settingsLogout">↪ Դուրս գալ</button></div>`);document.querySelector('#darkToggle').onclick=()=>toggleSetting('dark');document.querySelector('#soundToggle').onclick=()=>toggleSetting('sound');document.querySelector('#forgotSettings').onclick=passwordRecovery;document.querySelector('#backProfile').onclick=profilePanel;document.querySelector('#settingsLogout').onclick=logout}
function toggleSetting(key){const s=getSettings();s[key]=!s[key];saveSettings(s);if(key==='dark')document.documentElement.classList.toggle('light',!s.dark);settingsPanel();toast(key==='dark'?(s.dark?'Մութ էկրանը միացված է':'Բաց էկրանը միացված է'):(s.sound?'Հաղորդագրության ձայնը միացված է':'Հաղորդագրության ձայնը անջատված է'))}
function logout(){localStorage.removeItem(SESSION_KEY);closeModal();refreshProfileUI();toast('Դուրս եկար հաշվից')}
function escapeHtml(s=''){return s.replace(/[&<>\'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function escapeAttr(s=''){return escapeHtml(s)}
function refreshProfileUI(){const u=currentUser(),b=document.querySelector('#profileLabel');if(b)b.textContent=u?u.name:'Մուտք'}
document.addEventListener('DOMContentLoaded',()=>{const s=getSettings();document.documentElement.classList.toggle('light',!s.dark);refreshProfileUI();document.querySelector('#profileBtn').onclick=()=>currentUser()?profilePanel():authPanel('register')});
