const express=require('express');const cors=require('cors');const nodemailer=require('nodemailer');const crypto=require('crypto');const app=express();app.use(cors());app.use(express.json());
const PORT=process.env.PORT||3000;
const transporter=nodemailer.createTransport({host:process.env.SMTP_HOST||'smtp.gmail.com',port:Number(process.env.SMTP_PORT||465),secure:String(process.env.SMTP_SECURE||'true')==='true',auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASSWORD}});
const users=new Map();const resets=new Map();
function id(){let x;do{x=String(Math.floor(100000+Math.random()*900000))}while([...users.values()].some(u=>u.id===x));return x}
function base(req){return process.env.PUBLIC_URL||`${req.protocol}://${req.get('host')}`}
app.get('/',(req,res)=>res.json({service:'NyroxHub API',status:'online',message:'NyroxHub backend is running'}));
app.get('/health',(req,res)=>res.json({status:'ok',service:'NyroxHub email backend'}));
app.get('/api/health',(req,res)=>res.json({ok:true,service:'NyroxHub email backend'}));
app.post('/api/register',async(req,res)=>{try{const {name,email,password}=req.body||{};if(!name||!email||!password)return res.status(400).json({error:'Բոլոր դաշտերը պարտադիր են'});const e=email.trim().toLowerCase();if(users.has(e))return res.status(409).json({error:'Այս email-ը արդեն գրանցված է'});const user={id:id(),name:name.trim(),email:e,password,role:'user'};users.set(e,user);await transporter.sendMail({from:`NyroxHub <${process.env.SMTP_USER}>`,to:e,subject:'Շնորհակալություն NyroxHub-ում գրանցվելու համար 🎉',html:`<div style="font-family:Arial,sans-serif;max-width:620px;margin:auto;padding:32px;background:#0b1020;color:#fff;border-radius:18px"><h1>Բարի գալուստ NyroxHub 👋</h1><p>Շնորհակալություն գրանցվելու համար, <b>${user.name}</b>։</p><p>Քո NyroxHub ID-ն՝ <b style="color:#39d9ff">${user.id}</b></p><p>Քո հաշիվը ստեղծվել է հաջողությամբ։ Բարի խաղ։</p></div>`});res.status(201).json({id:user.id,name:user.name,role:user.role})}catch(e){console.error(e);res.status(500).json({error:'Հաշիվը ստեղծվեց, բայց email-ը չհաջողվեց ուղարկել։'})}});
app.post('/api/forgot-password',async(req,res)=>{try{const e=String(req.body?.email||'').trim().toLowerCase();const user=users.get(e);if(!user)return res.json({ok:true});const token=crypto.randomBytes(32).toString('hex');resets.set(token,{email:e,expires:Date.now()+15*60*1000});const link=`${base(req)}/reset-password.html?token=${token}`;await transporter.sendMail({from:`NyroxHub <${process.env.SMTP_USER}>`,to:e,subject:'NyroxHub — Գաղտնաբառի վերականգնում',html:`<div style="font-family:Arial,sans-serif;max-width:620px;margin:auto;padding:32px"><h2>Գաղտնաբառի վերականգնում</h2><p>Սեղմիր ստորև՝ նոր գաղտնաբառ սահմանելու համար։ Հղումը վավեր է 15 րոպե։</p><a href="${link}" style="display:inline-block;padding:13px 20px;background:#705cff;color:white;border-radius:10px;text-decoration:none">Վերականգնել գաղտնաբառը</a></div>`});res.json({ok:true})}catch(e){console.error(e);res.status(500).json({error:'Email ուղարկելը չհաջողվեց'})}});
app.post('/api/reset-password',async(req,res)=>{const {token,password}=req.body||{},r=resets.get(token);if(!r||r.expires<Date.now())return res.status(400).json({error:'Հղումը անվավեր է կամ ժամկետանց'});const u=users.get(r.email);if(!u)return res.status(400).json({error:'Օգտատերը չի գտնվել'});u.password=password;resets.delete(token);res.json({ok:true})});
app.post('/api/order-email',async(req,res)=>{try{const {email,name,product,quantity,total}=req.body||{};if(!email||!product)return res.status(400).json({error:'Missing order data'});await transporter.sendMail({from:`NyroxHub Store <${process.env.SMTP_USER}>`,to:email,subject:`NyroxHub — պատվերի հայտ ${product}`,html:`<div style="font-family:Arial,sans-serif;max-width:620px;margin:auto;padding:32px;background:#0b1020;color:#fff;border-radius:18px"><h2>Շնորհակալություն, ${name||'NyroxHub խաղացող'} 💙</h2><p>Քո գնման հայտը ստացվել է։</p><p><b>Ապրանք՝</b> ${product}<br><b>Քանակ՝</b> ${quantity||1}<br><b>Ընդհանուր՝</b> ${total||'—'} ֏</p><p>Վճարումը դեռ չի համարվում հաջողված։ Վերջնական հաստատումը կատարվում է NyPay-ի payment backend-ից։</p></div>`});res.json({ok:true})}catch(e){console.error(e);res.status(500).json({error:'Order email failed'})}});
app.listen(PORT,'0.0.0.0',()=>console.log(`NyroxHub backend listening on ${PORT}`));
