const express=require('express');const cors=require('cors');const nodemailer=require('nodemailer');const crypto=require('crypto');const app=express();app.use(cors({origin:true}));app.use(express.json({limit:'2mb'}));
const PORT=process.env.PORT||3000;const transporter=nodemailer.createTransport({host:process.env.SMTP_HOST||'smtp.gmail.com',port:Number(process.env.SMTP_PORT||465),secure:String(process.env.SMTP_SECURE||'true')==='true',auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASSWORD}});const users=new Map(),resets=new Map(),sessions=new Map();
function id(){let x;do{x=String(Math.floor(100000+Math.random()*900000))}while([...users.values()].some(u=>u.id===x));return x}function base(req){return process.env.PUBLIC_URL||`${req.protocol}://${req.get('host')}`}function hashPassword(password,salt=crypto.randomBytes(16).toString('hex')){return new Promise((resolve,reject)=>crypto.scrypt(password,salt,64,(e,k)=>e?reject(e):resolve(`${salt}:${k.toString('hex')}`)))}function checkPassword(password,stored){return new Promise((resolve,reject)=>{const [salt,hex]=String(stored).split(':');crypto.scrypt(password,salt,64,(e,k)=>{if(e)return reject(e);const a=Buffer.from(hex,'hex'),b=k;resolve(a.length===b.length&&crypto.timingSafeEqual(a,b))})})}function publicUser(u){return{id:u.id,name:u.name,email:u.email,role:u.role,logo:u.logo||''}}async function sendMail(to,subject,html){return transporter.sendMail({from:`NyroxHub <${process.env.SMTP_USER}>`,to,subject,html})}
app.get('/',(q,s)=>s.json({service:'NyroxHub API',status:'online'}));app.get('/health',(q,s)=>s.json({status:'ok'}));app.get('/api/health',(q,s)=>s.json({ok:true,service:'NyroxHub email backend'}));
app.post('/api/register',async(q,s)=>{try{const{name,email,password}=q.body||{};if(!name||!email||!password||password.length<8)return s.status(400).json({error:'Լրացրու բոլոր դաշտերը։ Գաղտնաբառը՝ առնվազն 8 նիշ։'});const e=email.trim().toLowerCase();if(users.has(e))return s.status(409).json({error:'Այս email-ը արդեն գրանցված է'});const u={id:id(),name:name.trim(),email:e,password:await hashPassword(password),role:'user',logo:''};users.set(e,u);const token=crypto.randomBytes(32).toString('hex');sessions.set(token,{email:e,expires:Date.now()+604800000});await sendMail(e,'Շնորհակալություն NyroxHub-ում գրանցվելու համար 🎉',`<div style="font-family:Arial;max-width:620px;margin:auto;padding:32px;background:#0b1020;color:white;border-radius:18px"><h1>Բարի գալուստ NyroxHub 👋</h1><p>Շնորհակալություն գրանցվելու համար, <b>${u.name}</b>։</p><p>Քո NyroxHub ID-ն՝ <b style="color:#39d9ff">${u.id}</b></p><p>Քո հաշիվը ստեղծվել է հաջողությամբ։ Բարի խաղ։</p></div>`);s.status(201).json({user:publicUser(u),token})}catch(e){console.error(e);s.status(500).json({error:'Գրանցումը կամ email-ը չհաջողվեց։'})}});
app.post('/api/login',async(q,s)=>{try{const{email,password}=q.body||{},e=String(email||'').trim().toLowerCase(),u=users.get(e);if(!u||!(await checkPassword(String(password||''),u.password)))return s.status(401).json({error:'Email-ը կամ գաղտնաբառը սխալ է'});const token=crypto.randomBytes(32).toString('hex');sessions.set(token,{email:e,expires:Date.now()+604800000});s.json({user:publicUser(u),token})}catch(e){console.error(e);s.status(500).json({error:'Մուտքը չհաջողվեց'})}});
app.post('/api/forgot-password',async(q,s)=>{try{const e=String(q.body?.email||'').trim().toLowerCase(),u=users.get(e);if(!u)return s.json({ok:true});const token=crypto.randomBytes(32).toString('hex');resets.set(token,{email:e,expires:Date.now()+900000});const link=`${base(q)}/reset-password.html?token=${token}`;await sendMail(e,'NyroxHub — Գաղտնաբառի վերականգնում',`<div style="font-family:Arial;max-width:620px;margin:auto;padding:32px"><h2>Գաղտնաբառի վերականգնում</h2><p>Բարև, ${u.name}։ Հղումը վավեր է 15 րոպե։</p><a href="${link}" style="display:inline-block;padding:13px 20px;background:#705cff;color:white;border-radius:10px;text-decoration:none">Վերականգնել գաղտնաբառը</a></div>`);s.json({ok:true})}catch(e){console.error(e);s.status(500).json({error:'Email ուղարկելը չհաջողվեց'})}});
app.post('/api/reset-password',async(q,s)=>{try{const{token,password}=q.body||{},r=resets.get(token);if(!r||r.expires<Date.now())return s.status(400).json({error:'Հղումը անվավեր է կամ ժամկետանց'});if(!password||password.length<8)return s.status(400).json({error:'Գաղտնաբառը՝ առնվազն 8 նիշ'});const u=users.get(r.email);if(!u)return s.status(400).json({error:'Օգտատերը չի գտնվել'});u.password=await hashPassword(password);resets.delete(token);s.json({ok:true})}catch(e){s.status(500).json({error:'Գաղտնաբառը չհաջողվեց փոխել'})}});
app.post('/api/order-email',async(q,s)=>{try{const{email,name,product,quantity,total}=q.body||{};if(!email||!product)return s.status(400).json({error:'Missing order data'});await sendMail(email,`NyroxHub — պատվերի հայտ ${product}`,`<div style="font-family:Arial;max-width:620px;margin:auto;padding:32px;background:#0b1020;color:white;border-radius:18px"><h2>Շնորհակալություն, ${name||'NyroxHub խաղացող'} 💙</h2><p>Քո գնման հայտը ստացվել է։</p><p><b>Ապրանք՝</b> ${product}<br><b>Քանակ՝</b> ${quantity||1}<br><b>Ընդհանուր՝</b> ${total||'—'} ֏</p><p>Վճարումը դեռ չի համարվում հաջողված։ Վերջնական հաստատումը կատարվում է NyPay payment backend-ից։</p></div>`);s.json({ok:true})}catch(e){console.error(e);s.status(500).json({error:'Order email failed'})}});
app.listen(PORT,'0.0.0.0',()=>console.log(`NyroxHub backend listening on ${PORT}`));
